export const GET_DATA = 'GET_DATA';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VALIDATE_CODE = 'VALIDATE_CODE';
export const STORE_INFO = 'STORE_INFO';
export const GET_ALL_PASSIONS = 'GET_ALL_PASSIONS';
export const DUMMY_USER_SUCCESS = 'DUMMY_USER_SUCCESS';
export const DUMMY_USER_FAILURE = 'DUMMY_USER_FAILURE';
export const UPDATE_MY_USER_INFOS = 'UPDATE_MY_USER_INFOS';

export const PUBLISH_CONTRIBUTION = 'PUBLISH_CONTRIBUTION';
export const PUBLISH_WORK = 'PUBLISH_WORK';
export const GET_ALL_USER_WORKS = 'GET_ALL_USER_WORKS';
export const GET_ALL_USER_CONTRIBUTIONS = 'GET_ALL_USER_CONTRIBUTIONS';
export const GET_ALL_SUBSCRIPTION_CONTENT = 'GET_ALL_SUBSCRIPTION_CONTENT';
export const GET_ALL_ARTFORM_CONTENT = 'GET_ALL_ARTFORM_CONTENT';
export const GET_ALL_TRENDING_CONTENT = 'GET_ALL_TRENDING_CONTENT';
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';
export const GET_JOURNAL_CONTENT = 'GET_JOURNAL_CONTENT';
export const OPEN_JOURNAL = 'OPEN_JOURNAL';

export const PROMOTE_POST_SUCCESS = 'PROMOTE_POST_SUCCESS';
export const REACT_POST_SUCCESS = 'REACT_POST_SUCCESS';
export const GET_POST_REACTION_SUCCESS = 'GET_POST_REACTION_SUCCESS';

//Modals

export const OPEN_PROMOTE_POST_MODAL = 'OPEN_PROMOTE_POST_MODAL';
export const OPEN_REACT_TO_POST_MODAL = 'OPEN_REACT_TO_POST_MODAL';
export const OPEN_PUBLISH_CONTRIBUTION_MODAL =
	'OPEN_PUBLISH_CONTRIBUTION_MODAL';
export const OPEN_PUBLISH_WORK_MODAL = 'OPEN_PUBLISH_WORK_MODAL';
export const CLOSE_PROMOTE_POST_MODAL = 'CLOSE_PROMOTE_POST_MODAL';
export const CLOSE_REACT_TO_POST_MODAL = 'CLOSE_REACT_TO_POST_MODAL';
export const CLOSE_PUBLISH_CONTRIBUTION_MODAL =
	'CLOSE_PUBLISH_CONTRIBUTION_MODAL';
export const CLOSE_PUBLISH_WORK_MODAL = 'CLOSE_PUBLISH_WORK_MODAL';
export const OPEN_SHOW_PICTURE_MODAL = 'OPEN_SHOW_PICTURE_MODAL';
export const CLOSE_SHOW_PICTURE_MODAL = 'CLOSE_SHOW_PICTURE_MODAL';

//DELETE EDIT
export const DELETE_CONTRIBUTION = 'DELETE_CONTRIBUTION';
export const EDIT_CONTRIBUTION = 'EDIT_CONTRIBUTION';

//user
export const GET_MY_INFOS = 'GET_MY_INFOS';
export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';

//users
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USERS = 'GET_USERS';

//Subscription
export const UPDATE_SUBSCRIBTIONS = 'UPDATE_SUBSCRIBTIONS';
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const SUBSCRIBE_TO_USER = 'SUBSCRIBE_TO_USER';
export const UNSUBSCRIBE_FROM_USER = 'UNSUBSCRIBE_FROM_USER';

//Journals
export const CREATE_JOURNAL = 'CREATE_JOURNAL';
export const GET_MY_JOURNALS = 'GET_MY_JOURNALS';
export const DELETE_JOURNAL = 'DELETE_JOURNAL';

// Explore
export const EXPLORE_PASSIONS_LIST = 'EXPLORE_PASSIONS_LIST';
export const EXPLORE_FORMS_LIST = 'EXPLORE_FORMS_LIST';
export const EXPLORE_JOURNALS_LIST = 'EXPLORE_JOURNALS_LIST';
export const EXPLORE_SELECT_SECTION = 'EXPLORE_SELECT_SECTION';
export const EXPLORE_RESET_NAVIGATION = 'EXPLORE_RESET_NAVIGATION';
export const EXPLORE_RESET_JOURNAL_SELECTION = 'EXPLORE_RESET_JOURNAL_SELECTION';

// Content Page
export const CONTENT_PAGE_OPEN = 'CONTENT_PAGE_OPEN';
export const CONTENT_PAGE_RELOAD = 'CONTENT_PAGE_RELOAD';
export const GET_REACTIONS_LIST = 'GET_REACTIONS_LIST';

// Sidebar
export const SIDEBAR_GET_TRENDING = 'SIDEBAR_GET_TRENDING';
export const SIDEBAR_GET_ARTFORMS = 'SIDEBAR_GET_ARTFORMS';

export const CLEAR_FEED = 'CLEAR_FEED';

export const GET_AUDIENCE_START = "GET_AUDIENCE_START"
export const GET_AUDIENCE_SUCCESS = "GET_AUDIENCE_SUCCESS"
export const GET_AUDIENCE_FAIL = "GET_AUDIENCE_FAIL"